version: '3'

services:
  server:
    build:
      context: .
      dockerfile: docker-resources/Dockerfile_Server_Local
    ports:
      - "5000:5000"
    links:
      - "db:db"
    networks:
      - projectx
    env_file:
      - docker-resources/env/server.env
    volumes:
      - "./server/modules:/code/server/modules"
      - "./server/index.py:/code/index.py"
    command: [ "python", "-m", "flask", "run" ]
  db:
    image: postgres
    env_file:
      - docker-resources/env/db.env
    networks:
      - projectx
    ports:
      - "5432:5432"
    volumes:
      - projectx_db:/var/lib/postgresql/data

networks:
  projectx:

volumes:
  projectx_db: